---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install docker-ce
  yum:
    name: docker-ce
    state: installed

- name: install docker-ce-cli
  yum:
    name: docker-ce-cli
    state: installed

  - name: install container.io
  yum:
    name: container.io
    state: installed

- name: enable service docker
  service:
    name: docker
    enabled: yes
  notify: restart docker
