---
- name: install docker-ce
  yum:
    name: docker-ce
    state: installed

- name: install docker-ce-cli
  yum:
    name: docker-ce-cli
    state: installed

- name: install containerd.io
  yum:
    name: containerd.io
    state: installed

- name: enable service docker
  service:
    name: docker
    enabled: yes
  notify: restart docker