---
- name: add repo
  command: yum-config-manager --add-repo=https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install consul
  yum:
    name: consul
    state: installed

- name: add consul script
  template:
    src: consul.sh.j2
    dest: /etc/consul.d/consul.hcl
    owner: "consul"
    group: "consul"
    mode: 0744

- name: enable service consul
  service:
    name: consul
    enabled: yes
  notify: restart consul
