---
- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: docker repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker
  yum:
    name: docker-ce
    state: present
  become: yes

- name: install docker-ce-cli
  yum: 
    name: docker-ce-cli
    state: present

- name: install containerd.io
  yum:
    name: containerd.io
    state: present


- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes
