---
- name: install nomad
  yum:
    name: nomad
    state: installed

- name: add nomad script
  template:
    src: nomad.sh.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "root"
    group: "root"
    mode: 0744

- name: enable service nomad
  service:
    name: nomad
    enabled: yes
  notify: restart nomad
